

--THEM TAI KHOAN
create TRIGGER THEMTAIKHOAN ON TAIKHOAN INSTEAD OF INSERT
AS BEGIN
DECLARE @USERNAME VARCHAR(30), @PASSWORD VARCHAR(1000), @HOTEN NVARCHAR(50), @PHANQUYEN NVARCHAR(50)
SELECT @USERNAME = USERNAME, @PASSWORD = PASSWORD, @HOTEN = HOTEN, @PHANQUYEN = PHANQUYEN FROM inserted 
IF (SELECT COUNT(USERNAME) FROM TAIKHOAN WHERE USERNAME = @USERNAME) = 0
	INSERT INTO TAIKHOAN VALUES (@USERNAME, @PASSWORD, @HOTEN, @PHANQUYEN)
ELSE ROLLBACK
END
go

--THEM MON AN
CREATE PROCEDURE THEMMONAN
    @MAMA VARCHAR(10),
	@TENMONAN AS NVARCHAR(100),
	@DVT AS NVARCHAR(20),
	@DONGIA AS DECIMAL(18,0),
	@MALOAI VARCHAR(10)
AS
BEGIN
    INSERT INTO MONAN
	VALUES(@MAMA, @TENMONAN,@DVT, @DONGIA, @MALOAI)
END
GO

--SUA MON AN
CREATE PROCEDURE SUAMONAN
    @MAMA VARCHAR(10),
	@TENMONAN NVARCHAR(100),
	@DVT NVARCHAR(20),
	@DONGIA DECIMAL(18,0),
	@MALOAI VARCHAR(10)
AS
BEGIN
    UPDATE MONAN SET  TENMONAN=@TENMONAN, DVT=@DVT, DONGIA=@DONGIA, MALOAI=@MALOAI WHERE MAMA=@MAMA
END
GO

--XOA MON AN
create trigger XOAMONAN on MONAN  instead of delete
AS declare @mama VARCHAR(10)
BEGIN
SELECT @mama = MAMA FROM deleted
DELETE FROM CHITIETDATMON WHERE MAMA = @mama
DELETE FROM MONAN WHERE MAMA = @mama
END
go

--THEM LOAI MON
CREATE PROCEDURE THEMLOAIMON
    @MALOAI VARCHAR(10),
	@TENLOAIMON NVARCHAR(50)
AS
BEGIN
    INSERT INTO LOAIMON
    VALUES
    (   @MALOAI, @TENLOAIMON )
END
GO

--SUA LOAI MON
CREATE PROCEDURE dbo.SUALOAIMON
    @MALOAI VARCHAR(10),
	@TENLOAIMON NVARCHAR(50)
AS
BEGIN
    UPDATE LOAIMON SET TENLOAIMON=@TENLOAIMON WHERE MALOAI=@MALOAI
END
GO

--XOA LOAI MON
create trigger XOALOAIMON on LOAIMON  instead of delete
AS declare @MALOAI VARCHAR(10)
BEGIN
SELECT @MALOAI= MALOAI FROM deleted
DELETE FROM MONAN WHERE MALOAI = @MALOAI
DELETE FROM LOAIMON WHERE MALOAI = @MALOAI
END
go

-- TU TAO MA LOAI MON
CREATE FUNCTION TAOMALOAIMON()
RETURNS VARCHAR(10)
AS
BEGIN
DECLARE @MALM VARCHAR(10)
DECLARE @MAXMALM VARCHAR(10)
DECLARE @MAX INT
SELECT @MAXMALM = MAX(MALOAI) FROM LOAIMON
IF EXISTS (SELECT MALOAI FROM LOAIMON)
	SET @MAX = CONVERT(INT, SUBSTRING(@MAXMALM, 3 ,8))+1
ELSE SET @MAX = 1
IF (@MAX < 10) SET @MALM = 'LM0' + CONVERT (VARCHAR(1), @MAX)
ELSE
IF (@MAX < 100) SET @MALM = 'LM' + CONVERT (VARCHAR(2), @MAX)
RETURN @MALM
END

-- TU TAO MA MON
CREATE FUNCTION TAOMAMON()
RETURNS VARCHAR(10)
AS
BEGIN
DECLARE @MAMA VARCHAR(10)
DECLARE @MAXMAMA VARCHAR(10)
DECLARE @MAX INT
SELECT @MAXMAMA = MAX(MAMA) FROM MONAN
IF EXISTS (SELECT MAMA FROM MONAN)
	SET @MAX = CONVERT(INT, SUBSTRING(@MAXMAMA, 3 ,8))+1
ELSE SET @MAX = 1
IF (@MAX < 10) SET @MAMA = 'MM0' + CONVERT (VARCHAR(1), @MAX)
ELSE
IF (@MAX < 100) SET @MAMA = 'MM' + CONVERT (VARCHAR(2), @MAX)
RETURN @MAMA
END